namespace SkillMultiplier;

// Replaces the class normally generated by the BepInEx.PluginInfoProps source generator
// (classic-format csproj has no source generators).
internal static class MyPluginInfo
{
    public const string PLUGIN_GUID = "dazzuh.skillmultiplier";
    public const string PLUGIN_NAME = "SkillMultiplier";
    public const string PLUGIN_VERSION = "1.1.1";
}
