<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>IcyClawz.ItemContextMenuExt</AssemblyName>
    <Version>1.8.0</Version>
    <RootNamespace>IcyClawz.ItemContextMenuExt</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\Shared\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>..\Shared\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="Comfort">
      <HintPath>..\Shared\Comfort.dll</HintPath>
    </Reference>
    <Reference Include="IcyClawz.CustomInteractions">
      <HintPath>..\Shared\IcyClawz.CustomInteractions.dll</HintPath>
    </Reference>
    <Reference Include="ItemComponent.Types">
      <HintPath>..\Shared\ItemComponent.Types.dll</HintPath>
    </Reference>
    <Reference Include="ItemTemplate.Types">
      <HintPath>..\Shared\ItemTemplate.Types.dll</HintPath>
    </Reference>
    <Reference Include="SPT.Reflection">
      <HintPath>..\Shared\spt-reflection.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\Shared\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\Shared\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
