<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>IcyClawz.ItemAttributeFix</AssemblyName>
    <Version>1.7.0</Version>
    <RootNamespace>IcyClawz.ItemAttributeFix</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\Shared\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>..\Shared\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="SPT.Reflection">
      <HintPath>..\Shared\spt-reflection.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\Shared\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\Shared\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
