<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <!-- D5：三段核心 + semver 预发布后缀，META-005 必须 PASS -->
    <Version>1.3.4-spt5.1</Version>
    <SPTInstallPath Condition="'$(SPTInstallPath)' == ''">C:\SPT</SPTInstallPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx" />
    <Reference Include="0Harmony" />
    <Reference Include="Assembly-CSharp" />
    <Reference Include="UnityEngine" />
  </ItemGroup>

</Project>
