<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MergeConsumables</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <Version>0.0.1</Version>
    <!-- The two lines below will set the output path for the binaries -->
    <OutputPath>bin\$(Configuration)\$(ProjectName)\$(AssemblyName)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SPTarkov.Common" Version="4.1.1" />
    <PackageReference Include="SPTarkov.DI" Version="4.1.1" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

	<Target Name="PostBuild" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
		<PropertyGroup>
			<PackageRoot>$(SolutionDir)release\package</PackageRoot>
			<PackageRootAddon>$(SolutionDir)releaseAddon\package</PackageRootAddon>
			<ZipOutput>$(SolutionDir)release\MergeConsumables.zip</ZipOutput>
			<ZipOutputAddon>$(SolutionDir)release\MergeConsumablesFika.zip</ZipOutputAddon>
		</PropertyGroup>

		<!-- Clean output -->
		<RemoveDir Directories="$(PackageRoot)" />
		<RemoveDir Directories="$(PackageRootAddon)" />

		<!-- Recreate structure -->
		<MakeDir Directories="$(PackageRoot)\SPT_Runtime\user\mods\MergeConsumablesServer" />
		<MakeDir Directories="$(PackageRoot)\BepInEx\plugins\MergeConsumables" />

		<MakeDir Directories="$(PackageRootAddon)\BepInEx\plugins\MergeConsumables" />

		<!-- Copy DLLs -->
		<Copy SourceFiles="$(SolutionDir)bin\Release\MergeConsumables.dll" DestinationFolder="$(PackageRoot)\BepInEx\plugins\MergeConsumables" />

		<Copy SourceFiles="$(ProjectDir)\bin\$(Configuration)\MergeConsumablesServer\MergeConsumablesServer.dll" DestinationFolder="$(PackageRoot)\SPT_Runtime\user\mods\MergeConsumablesServer" />

		<Copy SourceFiles="$(SolutionDir)fika\bin\$(Configuration)\netstandard2.1\MergeConsumablesFika.dll" DestinationFolder="$(PackageRootAddon)\BepInEx\plugins\MergeConsumables" />

		<!-- Copy LICENSE.md -->
		<Copy SourceFiles="$(SolutionDir)\LICENSE.md" DestinationFolder="$(PackageRoot)\SPT_Runtime\user\mods\MergeConsumablesServer" />

		<Copy SourceFiles="$(SolutionDir)\LICENSE.md" DestinationFolder="$(PackageRoot)\BepInEx\plugins\MergeConsumables" />

		<Copy SourceFiles="$(SolutionDir)\LICENSE.md" DestinationFolder="$(PackageRootAddon)\BepInEx\plugins\MergeConsumables" />

		<!-- Create the zip -->
		<ZipDirectory SourceDirectory="$(PackageRoot)" DestinationFile="$(ZipOutput)" Overwrite="true" />

		<!-- Create the addon zip -->
		<ZipDirectory SourceDirectory="$(PackageRootAddon)" DestinationFile="$(ZipOutputAddon)" Overwrite="true" />
	</Target>

</Project>